# Add house
POST http://localhost:3000/api/v1/house
Content-Type: application/json

{
    "name": "test",
    "country": "UA",
    "city": "city",
    "street_line_1": "line 1",
    "street_line_2": "line 2"
}
###

# Get All
GET http://localhost:3000/api/v1/house
###

#Find by id
GET http://localhost:3000/api/v1/house/a2785f26-40b3-11ec-b10a-acde48001122
###