// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	errors "github.com/VlasovArtem/hob/src/common/errors"
	mock "github.com/stretchr/testify/mock"

	model "github.com/VlasovArtem/hob/src/user/model"
)

// UserRequestValidator is an autogenerated mock type for the UserRequestValidator type
type UserRequestValidator struct {
	mock.Mock
}

// ValidateCreateRequest provides a mock function with given fields: request
func (_m *UserRequestValidator) ValidateCreateRequest(request model.CreateUserRequest) errors.ErrorResponse {
	ret := _m.Called(request)

	var r0 errors.ErrorResponse
	if rf, ok := ret.Get(0).(func(model.CreateUserRequest) errors.ErrorResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.ErrorResponse)
		}
	}

	return r0
}
