// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "payment/scheduler/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PaymentSchedulerRepository is an autogenerated mock type for the PaymentSchedulerRepository type
type PaymentSchedulerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: scheduler
func (_m *PaymentSchedulerRepository) Create(scheduler model.PaymentScheduler) (model.PaymentScheduler, error) {
	ret := _m.Called(scheduler)

	var r0 model.PaymentScheduler
	if rf, ok := ret.Get(0).(func(model.PaymentScheduler) model.PaymentScheduler); ok {
		r0 = rf(scheduler)
	} else {
		r0 = ret.Get(0).(model.PaymentScheduler)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.PaymentScheduler) error); ok {
		r1 = rf(scheduler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteById provides a mock function with given fields: id
func (_m *PaymentSchedulerRepository) DeleteById(id uuid.UUID) {
	_m.Called(id)
}

// ExistsById provides a mock function with given fields: id
func (_m *PaymentSchedulerRepository) ExistsById(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindByHouseId provides a mock function with given fields: houseId
func (_m *PaymentSchedulerRepository) FindByHouseId(houseId uuid.UUID) []model.PaymentScheduler {
	ret := _m.Called(houseId)

	var r0 []model.PaymentScheduler
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.PaymentScheduler); ok {
		r0 = rf(houseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PaymentScheduler)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *PaymentSchedulerRepository) FindById(id uuid.UUID) (model.PaymentScheduler, error) {
	ret := _m.Called(id)

	var r0 model.PaymentScheduler
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.PaymentScheduler); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.PaymentScheduler)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: userId
func (_m *PaymentSchedulerRepository) FindByUserId(userId uuid.UUID) []model.PaymentScheduler {
	ret := _m.Called(userId)

	var r0 []model.PaymentScheduler
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.PaymentScheduler); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PaymentScheduler)
		}
	}

	return r0
}
