// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	db "github.com/VlasovArtem/hob/src/db"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/VlasovArtem/hob/src/pivotal/repository"

	uuid "github.com/google/uuid"
)

// PivotalRepository is an autogenerated mock type for the PivotalRepository type
type PivotalRepository[T interface{}] struct {
	mock.Mock
}

// Create provides a mock function with given fields: value, omit
func (_m *PivotalRepository[T]) Create(value interface{}, omit ...string) error {
	_va := make([]interface{}, len(omit))
	for _i := range omit {
		_va[_i] = omit[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...string) error); ok {
		r0 = rf(value, omit...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB provides a mock function with given fields:
func (_m *PivotalRepository[T]) DB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// DBModeled provides a mock function with given fields: model
func (_m *PivotalRepository[T]) DBModeled(model interface{}) *gorm.DB {
	ret := _m.Called(model)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(interface{}) *gorm.DB); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *PivotalRepository[T]) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: id
func (_m *PivotalRepository[T]) Exists(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExistsBy provides a mock function with given fields: query, args
func (_m *PivotalRepository[T]) ExistsBy(query interface{}, args ...interface{}) bool {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) bool); ok {
		r0 = rf(query, args...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *PivotalRepository[T]) Find(id uuid.UUID) (T, error) {
	ret := _m.Called(id)

	var r0 T
	if rf, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(T)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBy provides a mock function with given fields: query, conditions
func (_m *PivotalRepository[T]) FindBy(query interface{}, conditions ...interface{}) (T, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 T
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) T); ok {
		r0 = rf(query, conditions...)
	} else {
		r0 = ret.Get(0).(T)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, conditions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySourceId provides a mock function with given fields: sourceId, source
func (_m *PivotalRepository[T]) FindBySourceId(sourceId uuid.UUID, source *T) error {
	ret := _m.Called(sourceId, source)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *T) error); ok {
		r0 = rf(sourceId, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindReceiver provides a mock function with given fields: receiver, id
func (_m *PivotalRepository[T]) FindReceiver(receiver interface{}, id uuid.UUID) error {
	ret := _m.Called(receiver, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uuid.UUID) error); ok {
		r0 = rf(receiver, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindReceiverBy provides a mock function with given fields: receiver, query, conditions
func (_m *PivotalRepository[T]) FindReceiverBy(receiver interface{}, query interface{}, conditions ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, receiver, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}, ...interface{}) error); ok {
		r0 = rf(receiver, query, conditions...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// First provides a mock function with given fields: id
func (_m *PivotalRepository[T]) First(id uuid.UUID) (T, error) {
	ret := _m.Called(id)

	var r0 T
	if rf, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(T)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstBy provides a mock function with given fields: query, conditions
func (_m *PivotalRepository[T]) FirstBy(query interface{}, conditions ...interface{}) (T, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 T
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) T); ok {
		r0 = rf(query, conditions...)
	} else {
		r0 = ret.Get(0).(T)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, conditions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstReceiver provides a mock function with given fields: receiver, id
func (_m *PivotalRepository[T]) FirstReceiver(receiver interface{}, id uuid.UUID) error {
	ret := _m.Called(receiver, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uuid.UUID) error); ok {
		r0 = rf(receiver, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FirstReceiverBy provides a mock function with given fields: receiver, query, conditions
func (_m *PivotalRepository[T]) FirstReceiverBy(receiver interface{}, query interface{}, conditions ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, receiver, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}, ...interface{}) error); ok {
		r0 = rf(receiver, query, conditions...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEntity provides a mock function with given fields:
func (_m *PivotalRepository[T]) GetEntity() T {
	ret := _m.Called()

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(T)
	}

	return r0
}

// GetProvider provides a mock function with given fields:
func (_m *PivotalRepository[T]) GetProvider() db.ProviderInterface {
	ret := _m.Called()

	var r0 db.ProviderInterface
	if rf, ok := ret.Get(0).(func() db.ProviderInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.ProviderInterface)
		}
	}

	return r0
}

// Modeled provides a mock function with given fields:
func (_m *PivotalRepository[T]) Modeled() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Transactional provides a mock function with given fields: tx
func (_m *PivotalRepository[T]) Transactional(tx *gorm.DB) repository.PivotalRepository[T] {
	ret := _m.Called(tx)

	var r0 repository.PivotalRepository[T]
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.PivotalRepository[T]); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PivotalRepository[T])
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, entity, omit
func (_m *PivotalRepository[T]) Update(id uuid.UUID, entity interface{}, omit ...string) error {
	_va := make([]interface{}, len(omit))
	for _i := range omit {
		_va[_i] = omit[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id, entity)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, interface{}, ...string) error); ok {
		r0 = rf(id, entity, omit...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPivotalRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPivotalRepository creates a new instance of PivotalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPivotalRepository[T interface{}](t mockConstructorTestingTNewPivotalRepository) *PivotalRepository[T] {
	mock := &PivotalRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
