// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/VlasovArtem/hob/src/group/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GroupRepository is an autogenerated mock type for the GroupRepository type
type GroupRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: entity
func (_m *GroupRepository) Create(entity model.Group) (model.Group, error) {
	ret := _m.Called(entity)

	var r0 model.Group
	if rf, ok := ret.Get(0).(func(model.Group) model.Group); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(model.Group)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Group) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteById provides a mock function with given fields: id
func (_m *GroupRepository) DeleteById(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsById provides a mock function with given fields: id
func (_m *GroupRepository) ExistsById(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *GroupRepository) FindById(id uuid.UUID) (model.GroupDto, error) {
	ret := _m.Called(id)

	var r0 model.GroupDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.GroupDto); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.GroupDto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOwnerId provides a mock function with given fields: ownerId
func (_m *GroupRepository) FindByOwnerId(ownerId uuid.UUID) []model.GroupDto {
	ret := _m.Called(ownerId)

	var r0 []model.GroupDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.GroupDto); ok {
		r0 = rf(ownerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupDto)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, request
func (_m *GroupRepository) Update(id uuid.UUID, request model.UpdateGroupRequest) error {
	ret := _m.Called(id, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, model.UpdateGroupRequest) error); ok {
		r0 = rf(id, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
