// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "payment/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// Add provides a mock function with given fields: request
func (_m *PaymentService) Add(request model.CreatePaymentRequest) (model.PaymentDto, error) {
	ret := _m.Called(request)

	var r0 model.PaymentDto
	if rf, ok := ret.Get(0).(func(model.CreatePaymentRequest) model.PaymentDto); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(model.PaymentDto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.CreatePaymentRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsById provides a mock function with given fields: id
func (_m *PaymentService) ExistsById(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindByHouseId provides a mock function with given fields: HouseId
func (_m *PaymentService) FindByHouseId(houseId uuid.UUID) []model.PaymentDto {
	ret := _m.Called(houseId)

	var r0 []model.PaymentDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.PaymentDto); ok {
		r0 = rf(houseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PaymentDto)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *PaymentService) FindById(id uuid.UUID) (model.PaymentDto, error) {
	ret := _m.Called(id)

	var r0 model.PaymentDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.PaymentDto); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.PaymentDto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: UserId
func (_m *PaymentService) FindByUserId(userId uuid.UUID) []model.PaymentDto {
	ret := _m.Called(userId)

	var r0 []model.PaymentDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.PaymentDto); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PaymentDto)
		}
	}

	return r0
}
