// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/VlasovArtem/hob/src/income/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IncomeRepository is an autogenerated mock type for the IncomeRepository type
type IncomeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: entity
func (_m *IncomeRepository) Create(entity model.Income) (model.Income, error) {
	ret := _m.Called(entity)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(model.Income) model.Income); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Income) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindResponseByHouseId provides a mock function with given fields: id
func (_m *IncomeRepository) FindResponseByHouseId(id uuid.UUID) []model.IncomeResponse {
	ret := _m.Called(id)

	var r0 []model.IncomeResponse
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.IncomeResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IncomeResponse)
		}
	}

	return r0
}

// FindResponseById provides a mock function with given fields: id
func (_m *IncomeRepository) FindResponseById(id uuid.UUID) (model.IncomeResponse, error) {
	ret := _m.Called(id)

	var r0 model.IncomeResponse
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.IncomeResponse); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.IncomeResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
