// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	db "github.com/VlasovArtem/hob/src/db"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/VlasovArtem/hob/src/income/model"

	repository "github.com/VlasovArtem/hob/src/income/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// IncomeRepository is an autogenerated mock type for the IncomeRepository type
type IncomeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: value, omit
func (_m *IncomeRepository) Create(value interface{}, omit ...string) error {
	_va := make([]interface{}, len(omit))
	for _i := range omit {
		_va[_i] = omit[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...string) error); ok {
		r0 = rf(value, omit...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DB provides a mock function with given fields:
func (_m *IncomeRepository) DB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// DBModeled provides a mock function with given fields: _a0
func (_m *IncomeRepository) DBModeled(_a0 interface{}) *gorm.DB {
	ret := _m.Called(_a0)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(interface{}) *gorm.DB); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *IncomeRepository) Delete(id uuid.UUID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: id
func (_m *IncomeRepository) Exists(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExistsBy provides a mock function with given fields: query, args
func (_m *IncomeRepository) ExistsBy(query interface{}, args ...interface{}) bool {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) bool); ok {
		r0 = rf(query, args...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *IncomeRepository) Find(id uuid.UUID) (model.Income, error) {
	ret := _m.Called(id)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.Income); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBy provides a mock function with given fields: query, conditions
func (_m *IncomeRepository) FindBy(query interface{}, conditions ...interface{}) (model.Income, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) model.Income); ok {
		r0 = rf(query, conditions...)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, conditions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByGroupIds provides a mock function with given fields: groupIds, limit, offset, from, to
func (_m *IncomeRepository) FindByGroupIds(groupIds []uuid.UUID, limit int, offset int, from *time.Time, to *time.Time) ([]model.IncomeDto, error) {
	ret := _m.Called(groupIds, limit, offset, from, to)

	var r0 []model.IncomeDto
	if rf, ok := ret.Get(0).(func([]uuid.UUID, int, int, *time.Time, *time.Time) []model.IncomeDto); ok {
		r0 = rf(groupIds, limit, offset, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IncomeDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]uuid.UUID, int, int, *time.Time, *time.Time) error); ok {
		r1 = rf(groupIds, limit, offset, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByHouseId provides a mock function with given fields: id, limit, offset, from, to
func (_m *IncomeRepository) FindByHouseId(id uuid.UUID, limit int, offset int, from *time.Time, to *time.Time) ([]model.IncomeDto, error) {
	ret := _m.Called(id, limit, offset, from, to)

	var r0 []model.IncomeDto
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, *time.Time, *time.Time) []model.IncomeDto); ok {
		r0 = rf(id, limit, offset, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.IncomeDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, *time.Time, *time.Time) error); ok {
		r1 = rf(id, limit, offset, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *IncomeRepository) FindById(id uuid.UUID) (model.Income, error) {
	ret := _m.Called(id)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.Income); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindReceiver provides a mock function with given fields: receiver, id
func (_m *IncomeRepository) FindReceiver(receiver interface{}, id uuid.UUID) error {
	ret := _m.Called(receiver, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uuid.UUID) error); ok {
		r0 = rf(receiver, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindReceiverBy provides a mock function with given fields: receiver, query, conditions
func (_m *IncomeRepository) FindReceiverBy(receiver interface{}, query interface{}, conditions ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, receiver, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}, ...interface{}) error); ok {
		r0 = rf(receiver, query, conditions...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// First provides a mock function with given fields: id
func (_m *IncomeRepository) First(id uuid.UUID) (model.Income, error) {
	ret := _m.Called(id)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.Income); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstBy provides a mock function with given fields: query, conditions
func (_m *IncomeRepository) FirstBy(query interface{}, conditions ...interface{}) (model.Income, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 model.Income
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) model.Income); ok {
		r0 = rf(query, conditions...)
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, ...interface{}) error); ok {
		r1 = rf(query, conditions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FirstReceiver provides a mock function with given fields: receiver, id
func (_m *IncomeRepository) FirstReceiver(receiver interface{}, id uuid.UUID) error {
	ret := _m.Called(receiver, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uuid.UUID) error); ok {
		r0 = rf(receiver, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FirstReceiverBy provides a mock function with given fields: receiver, query, conditions
func (_m *IncomeRepository) FirstReceiverBy(receiver interface{}, query interface{}, conditions ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, receiver, query)
	_ca = append(_ca, conditions...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}, ...interface{}) error); ok {
		r0 = rf(receiver, query, conditions...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEntity provides a mock function with given fields:
func (_m *IncomeRepository) GetEntity() model.Income {
	ret := _m.Called()

	var r0 model.Income
	if rf, ok := ret.Get(0).(func() model.Income); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.Income)
	}

	return r0
}

// GetProvider provides a mock function with given fields:
func (_m *IncomeRepository) GetProvider() db.ProviderInterface {
	ret := _m.Called()

	var r0 db.ProviderInterface
	if rf, ok := ret.Get(0).(func() db.ProviderInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.ProviderInterface)
		}
	}

	return r0
}

// Modeled provides a mock function with given fields:
func (_m *IncomeRepository) Modeled() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Transactional provides a mock function with given fields: tx
func (_m *IncomeRepository) Transactional(tx *gorm.DB) repository.IncomeRepository {
	ret := _m.Called(tx)

	var r0 repository.IncomeRepository
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.IncomeRepository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.IncomeRepository)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, entity, omit
func (_m *IncomeRepository) Update(id uuid.UUID, entity interface{}, omit ...string) error {
	_va := make([]interface{}, len(omit))
	for _i := range omit {
		_va[_i] = omit[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, id, entity)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, interface{}, ...string) error); ok {
		r0 = rf(id, entity, omit...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateByRequest provides a mock function with given fields: id, request
func (_m *IncomeRepository) UpdateByRequest(id uuid.UUID, request model.UpdateIncomeRequest) error {
	ret := _m.Called(id, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, model.UpdateIncomeRequest) error); ok {
		r0 = rf(id, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIncomeRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIncomeRepository creates a new instance of IncomeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIncomeRepository(t mockConstructorTestingTNewIncomeRepository) *IncomeRepository {
	mock := &IncomeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
