// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "provider/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ProviderRepository is an autogenerated mock type for the ProviderRepository type
type ProviderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: provider
func (_m *ProviderRepository) Create(provider model.Provider) (model.Provider, error) {
	ret := _m.Called(provider)

	var r0 model.Provider
	if rf, ok := ret.Get(0).(func(model.Provider) model.Provider); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Get(0).(model.Provider)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Provider) error); ok {
		r1 = rf(provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsById provides a mock function with given fields: id
func (_m *ProviderRepository) ExistsById(id uuid.UUID) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ExistsByName provides a mock function with given fields: name
func (_m *ProviderRepository) ExistsByName(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *ProviderRepository) FindById(id uuid.UUID) (model.Provider, error) {
	ret := _m.Called(id)

	var r0 model.Provider
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.Provider); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Provider)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNameLike provides a mock function with given fields: namePattern, page, limit
func (_m *ProviderRepository) FindByNameLike(namePattern string, page int, limit int) []model.Provider {
	ret := _m.Called(namePattern, page, limit)

	var r0 []model.Provider
	if rf, ok := ret.Get(0).(func(string, int, int) []model.Provider); ok {
		r0 = rf(namePattern, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Provider)
		}
	}

	return r0
}
