// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "provider/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ProviderService is an autogenerated mock type for the ProviderService type
type ProviderService struct {
	mock.Mock
}

// Add provides a mock function with given fields: request
func (_m *ProviderService) Add(request model.CreateProviderRequest) (model.ProviderDto, error) {
	ret := _m.Called(request)

	var r0 model.ProviderDto
	if rf, ok := ret.Get(0).(func(model.CreateProviderRequest) model.ProviderDto); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(model.ProviderDto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.CreateProviderRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *ProviderService) FindById(id uuid.UUID) (model.ProviderDto, error) {
	ret := _m.Called(id)

	var r0 model.ProviderDto
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.ProviderDto); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.ProviderDto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNameLike provides a mock function with given fields: namePattern, page, size
func (_m *ProviderService) FindByNameLike(namePattern string, page int, size int) []model.ProviderDto {
	ret := _m.Called(namePattern, page, size)

	var r0 []model.ProviderDto
	if rf, ok := ret.Get(0).(func(string, int, int) []model.ProviderDto); ok {
		r0 = rf(namePattern, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderDto)
		}
	}

	return r0
}
